name: voltage_imaging_pipeline
channels:
  - oxfordcontrol
  - defaults
dependencies:
  - paramiko=2.8.1
  - xmltodict=0.12.0
  - tifffile=2021.7.2
  - matplotlib=3.7.1
  - plotly=5.9.0
  - streamlit=1.16.0
  - opencv=4.6.0
  - scipy=1.10.1
